services:
  crmapi.api:
    image: ${DOCKER_REGISTRY-}crmapiapi
    build:
      context: .
      dockerfile: CrmApi.Api/Dockerfile

  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: